name: Dart Format
on: workflow_dispatch
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'
      - run: flutter --version

      - name: Install dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format .
        
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi)
      - name: Update changes in GitHub repository
        if: steps.git-check.outputs.modified == 'true'
        uses: EndBug/add-and-commit@v9
        with:
            author_name: dreamerminsk
            author_email: tutmirage@gmail.com
            message: 'dart format'
