name: Releases

on: 
  push:
    tags:
    - '*'
  
jobs:
  releases:
    name: release apk
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: "20.0"
      FLUTTER_VERSION: "3.24.3"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '20.x'
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3"
          channel: 'stable'
          cache: true
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      - run: flutter build apk
      - uses: ncipollo/release-action@v1
        with:
         allowUpdates: true
         artifacts: "build/app/outputs/apk/release/*.apk"
         token: ${{ secrets.GITHUB_TOKEN }}
